apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  serviceName: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      terminationGracePeriodSeconds: 1800
      initContainers:
      - image: busybox
        name: fix-non-root-permissions
        command:
        - chmod
        - "-R"
 	- runAsUser:fsgroup
        - g+rwX
        - /bitnami
        imagePullPolicy: Always
        volumeMounts:
        - name: cassandra-data
	  mountPath: /bitnami
      containers:
      - image: "bitnami/cassandra:latest"
        imagePullPolicy: Always
        name: cassandra
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
	env:
        - name: MAX_HEAP_SIZE
          value: 512M
        - name: HEAP_NEWSIZE
          value: 100M
        - name: CASSANDRA_SEEDS
          value: cassandra-0.cassandra.default.svc.cluster.local
        - name: CASSANDRA_CLUSTER_NAME
          value: "Evs Dev"
        - name: CASSANDRA_DC
          value: DC1
        - name: CASSANDRA_RACK
          value: Rack1-EvsDev
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
	readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /ready-probe.sh
          initialDelaySeconds: 15
          timeoutSeconds: 5
        # These volume mounts are persistent. They are like inline claims,
        # but not exactly because the names need to match exactly one of
        # the stateful pod volumes.
        volumeMounts:
        - mountPath: /bitnami/cassandra
          name: cassandra-data
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes:
      - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: gp2
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-ssd
