apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  serviceName: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
	  initContainers:
        -
          command:
            - chmod
			- "-R"
			- runAsUser:fsgroup
            - g+rwX
            - /bitnami
          image: busybox
          imagePullPolicy: Always
          name: fix-non-root-permissions
          volumeMounts:
            -
              mountPath: /bitnami
              name: cassandra-data
      containers:
        -
          env:
            -
              name: MAX_HEAP_SIZE
              value: 512M
            -
              name: HEAP_NEWSIZE
              value: 100M
            -
              name: CASSANDRA_SEEDS
              value: cassandra-0.cassandra.default.svc.cluster.local
            -
              name: CASSANDRA_CLUSTER_NAME
              value: "Evs Dev"
            -
              name: CASSANDRA_DC
              value: DC1
            -
              name: CASSANDRA_RACK
              value: Rack1-EvsDev
            -
              name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: "bitnami/cassandra:latest"
          imagePullPolicy: Always
          name: cassandra
          ports:
            -
              containerPort: 7000
              name: intra-node
            -
              containerPort: 7001
              name: tls-intra-node
            -
              containerPort: 7199
              name: jmx
            -
              containerPort: 9042
              name: cql
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            -
              mountPath: /bitnami/cassandra
              name: cassandra-data

      terminationGracePeriodSeconds: 1800
  volumeClaimTemplates:
    -
      metadata:
        name: cassandra-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: gp2

                               
