apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data-a
  labels:
    type: local
    app: cassandra
spec:
  storageClassName: gp2
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/cassandra/cassandra-data-a
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data-b
  labels:
    type: local
    app: cassandra
spec:
  storageClassName: gp2
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/cassandra/cassandra-data-b
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data-c
  labels:
    type: local
    app: cassandra
spec:
  storageClassName: gp2
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/cassandra/cassandra-data-c
  persistentVolumeReclaimPolicy: Recycle
